apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor
  namespace: rag-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestor
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      containers:
        - name: ingestor
          image: rag-ingestor:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: QDRANT_URL
              value: http://qdrant:6333
            - name: OLLAMA_BASE_URL
              value: http://host.minikube.internal:11434
---
apiVersion: v1
kind: Service
metadata:
  name: ingestor
  namespace: rag-app
spec:
  selector:
    app: ingestor
  ports:
    - port: 8000
      targetPort: 8000
