server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ingestor/ {
        proxy_pass http://ingestor:8000/;
    }

    location /api/query/ {
        proxy_pass http://query:8001/;
    }
}
